package com.liferay.tutorial.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.liferay.tutorial.model.TutorialStep;
import com.liferay.tutorial.service.TutorialStepService;
import com.liferay.tutorial.service.persistence.TutorialStepPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the tutorial step remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.tutorial.service.impl.TutorialStepServiceImpl}.
 * </p>
 *
 * @author Miroslav Ligas
 * @see com.liferay.tutorial.service.impl.TutorialStepServiceImpl
 * @see com.liferay.tutorial.service.TutorialStepServiceUtil
 * @generated
 */
public abstract class TutorialStepServiceBaseImpl extends BaseServiceImpl
    implements TutorialStepService, IdentifiableBean {
    @BeanReference(type = com.liferay.tutorial.service.TutorialStepLocalService.class)
    protected com.liferay.tutorial.service.TutorialStepLocalService tutorialStepLocalService;
    @BeanReference(type = com.liferay.tutorial.service.TutorialStepService.class)
    protected com.liferay.tutorial.service.TutorialStepService tutorialStepService;
    @BeanReference(type = TutorialStepPersistence.class)
    protected TutorialStepPersistence tutorialStepPersistence;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private TutorialStepServiceClpInvoker _clpInvoker = new TutorialStepServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link com.liferay.tutorial.service.TutorialStepServiceUtil} to access the tutorial step remote service.
     */

    /**
     * Returns the tutorial step local service.
     *
     * @return the tutorial step local service
     */
    public com.liferay.tutorial.service.TutorialStepLocalService getTutorialStepLocalService() {
        return tutorialStepLocalService;
    }

    /**
     * Sets the tutorial step local service.
     *
     * @param tutorialStepLocalService the tutorial step local service
     */
    public void setTutorialStepLocalService(
        com.liferay.tutorial.service.TutorialStepLocalService tutorialStepLocalService) {
        this.tutorialStepLocalService = tutorialStepLocalService;
    }

    /**
     * Returns the tutorial step remote service.
     *
     * @return the tutorial step remote service
     */
    public com.liferay.tutorial.service.TutorialStepService getTutorialStepService() {
        return tutorialStepService;
    }

    /**
     * Sets the tutorial step remote service.
     *
     * @param tutorialStepService the tutorial step remote service
     */
    public void setTutorialStepService(
        com.liferay.tutorial.service.TutorialStepService tutorialStepService) {
        this.tutorialStepService = tutorialStepService;
    }

    /**
     * Returns the tutorial step persistence.
     *
     * @return the tutorial step persistence
     */
    public TutorialStepPersistence getTutorialStepPersistence() {
        return tutorialStepPersistence;
    }

    /**
     * Sets the tutorial step persistence.
     *
     * @param tutorialStepPersistence the tutorial step persistence
     */
    public void setTutorialStepPersistence(
        TutorialStepPersistence tutorialStepPersistence) {
        this.tutorialStepPersistence = tutorialStepPersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();
    }

    public void destroy() {
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    @Override
    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return TutorialStep.class;
    }

    protected String getModelClassName() {
        return TutorialStep.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = tutorialStepPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
