package com.liferay.tutorial.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.tutorial.model.TutorialStep;
import com.liferay.tutorial.service.TutorialStepLocalServiceUtil;

/**
 * The extended model base implementation for the TutorialStep service. Represents a row in the &quot;Tutorial_TutorialStep&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TutorialStepImpl}.
 * </p>
 *
 * @author Miroslav Ligas
 * @see TutorialStepImpl
 * @see com.liferay.tutorial.model.TutorialStep
 * @generated
 */
public abstract class TutorialStepBaseImpl extends TutorialStepModelImpl
    implements TutorialStep {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a tutorial step model instance should use the {@link TutorialStep} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TutorialStepLocalServiceUtil.addTutorialStep(this);
        } else {
            TutorialStepLocalServiceUtil.updateTutorialStep(this);
        }
    }
}
